# Relevant literature {#rellit}

In this chapter, I will present the previous empirical research on how environmental policy decisions have widely affected consumers and economies. The second subsection will cover a variety of previous research that utilised similar methodologies I have used in this thesis. This chapter aims to provide a brief background on the topic and examples of previous similar uses of similar methodological frameworks.

## Effects of environmental policy {#effects}

There has been some research on the effects of carbon taxes in different fields. Nevertheless, not one is done as extensively in Finland. Previously \citet{palanne2021} studied the effects of carbon taxes on Finnish passenger car traffic. They studied how tax schemes affected the carpool and if the break-in higher gasoline taxes would affect the types of cars people would buy \citep{palanne2021}. Unfortunately, their results were not encouraging; they estimated that between 2013 and 2017, personal transport emissions decreased only about 2.3 per cent \citep{palanne2021}. Another paper by \citet{sahari2019} studied how Finnish consumers reacted to the changing electricity prices. She found out that the electricity prices had a noticeable impact on consumers' heating choices who were building or renovating their houses \citep{sahari2019}. Furthermore, she used the variability of the electric prices across Finland to estimate the consumers' price elasticity between more environmentally conscious and traditional household heating options \citep{sahari2019}. 

Another research done in the context of Nordic countries that had contrasting results is an article written by \citet{andersson2019}. The author studied the Swedish economy's response to the enaction of carbon tax in the 1990s. Andersson used a quasi-experiment to find significant reductions in carbon emissions after implementing a carbon tax in Sweden in 1991 \citep{andersson2019}. The carbon tax started as a relatively moderate fiscal policy but was later increased to more substantial heights \citep{andersson2019}. He also found that consumers reacted to carbon tax hikes more than just the market-driven price changes; these findings were achieved using a synthetic control \citep{andersson2019}. These findings are in interesting contention with the findings of Palanne and Sahari. Some studies have also concentrated on the Finnish economy in the same period as Anderson was in Sweden. For example, a working paper written by \citet{elbaum2021} focuses on the response of the Finnish economy to carbon taxes in the 1990s. It uses a similar approach as Andersson to estimate the causal impact of the carbon tax \citep{elbaum2021}. He found a similar reaction in the Finnish economy to Andersson's in Sweden \citep{elbaum2021}. These results could suggest that at the time of Palanne's and Sahari's research, the effects of carbon taxes were already embedded into the decision-making process of Finnish consumers. Also, it underlines the importance of understanding the historical processes behind the studies as the results seem to be substantially context-dependent.

Another study that takes a much broader view on the macroeconomic impacts of carbon taxes on European economies was written by \citet{metcalf2020}. They implemented a plethora of time-series analyses on different European countries before and after implementing different carbon taxes \citep{metcalf2020}. Interestingly they found negligible impacts on GDP growth or employment but a substantial reduction in greenhouse gas emissions \citep{metcalf2020}. \citet{metcalf2021} also published an article where he outlines a theoretical framework on how carbon taxes and other greenhouse gas reduction mechanisms can work and reviews prior theoretical literature on the topic. He adds an essential point to the previous literature; if the effects of additional emissions are uncertain, the policymakers should lean more on cap-and-trade models as these have a hard limit on the number of emissions possible to emit and thus lowering the risk of possible tipping point scenarios \citep{metcalf2021}. 

Similar non-significant effects on employment and total output as \citet{metcalf2020} were also reported by \citet{martin2014} when they studied the United Kingdom's carbon tax implementation on the industrial sector. They differentiated plants using micro-econometric methods that parsed out different tax burdens between them \citep{martin2014}. They did not find statistically significant evidence that this would have adverse outcomes for the treatment plants compared to their control counterparts \citep{martin2014}.

In their paper, \citet{acemoglu2016} reiterated the importance of a quick transition to decarbonise the economy. They based their model on microdata from the United States, contrasting to more macro-centric results of \citet{metcalf2020} and \citet{andersson2019}. The model formalised by \citeauthor{acemoglu2016} predicts that only using carbon taxes as the sole policy tool has a high welfare cost, in the long run, significantly lowering the discount rate of future welfare losses. They suggest that subsidies for clean technology and research were a cost-effective intervention to lower the disutility of future generations \citep{acemoglu2016}. Their model had a much longer time horizon than other studies, running more than two hundred years.
Furthermore, they take a prescriptive approach as most of the studies described above are descriptive \citep{acemoglu2016}. Their estimated optimal path relied heavily on public investment in less polluting technologies. They also stated that if they would relax the assumption of linear damages from the greenhouse gas pollution, their findings could also tilt to favour carbon taxes more \citep{acemoglu2016}. The research by Acemoglu also sidesteps the possibility of the cap-and-trade schemes and the possible effects of these schemes.

This exclusion of a widely used policy is in stark contrast with the main inspiration of my thesis, which is the research done by \citet{kaenzig2022}, who studied solely the effects of the European Union emission trading scheme on the European and, particularly, the United Kingdom's economy. He used the futures market to identify the structural shocks of carbon policy surprises in the constantly evolving carbon policy environment that is the European Union \citep{kaenzig2022}. He quantified the size of these carbon policy shocks to United Kingdom's economy using the structural vector autoregressive model \citep{kaenzig2022}. This kind of surprise estimation has been previously used in the time series analysis of oil markets. The futures are the markets' best guess for the future price of these carbon permits, given there are no transportation costs, and the risk tolerance of the seller and buyer are equal \citep{nakamura2018}. This way, Känzig could estimate the surprise felt by the markets using tight time steps around policy announcements of the European emission trading scheme \citep{kaenzig2022}. He found robust evidence of the carbon policy shock's substantial negative impacts on GDP growth and employment \citep{kaenzig2022}.

## Previous SVAR-IV research {#prevsvar}

Before developing the instrument, variable-based identification of the structural vector autoregression method will be discussed in chapter \@ref(econometrics). The structural vector autoregression models were widely used to analyse macroeconomic phenomena. They are an insightful tool for analysing dynamic interdependent systems. This is why they have been deployed, for example, in macroeconomics to study the responses to changes in monetary policy [@wolf2020svar]. Likewise, another widely researched field for macroeconomists is the reactions to the oil price shocks [@kilian2009not].

An essential study pioneering the usage of macroeconomic news as an instrument was done by @romer2010macroeconomic. The authors utilised the record of post-war tax reforms and the context of these reforms [@romer2010macroeconomic]. Using narrative methods, the researchers could get substantial and long-lasting effects on production and economic activity [@romer2010macroeconomic]. They found that changes in tax rates of $20\text{th}$ century the United States had substantial impulse responses to the total output [@romer2010macroeconomic].      

Both previous research traditions that have utilised SVARs have in common that identifying the shocks is complex due to the endogenous nature of these shocks [@kaenzig2021]. However, Känzig answered an ingenious way of sidestepping this endogeneity problem in his previous research in the realms of oil and carbon policies \citep{kaenzig2022,kaenzig2021}. Moreover, this identification strategy will be further elaborated in the chapter \@ref(inst), which is fully dedicated to the instrument variable [@kaenzig2022].

Another integral part of the methodology used by @kaenzig2022 is the SVAR-IV-based analysis that was first introduced in a lecture by \citet{stock2008s}. It was an ingenious way to identify the structural shocks using an external instrument \citep{stock2008s}. The methodology was developed further in research by \citet{stock2012disentangling} where they illustrated the propagation channels of the recession of 2007-2009. The evidence presented in the research of Stock and Watson supports the idea that financial collapse and tight monetary policy had a significant impact on the slow economic recovery \citep{stock2012disentangling}.

The SVAR-IV was used in the Finnish context by \citet{keranen2020identification}, where they examined the size of the fiscal multiplier of government spending. According to the authors, the most important finding in this study was the formation of an instrument variable \citep{keranen2020identification}. This instrument variable can have use in future research. However, the authors cautioned whether the instrument should be used as an external instrument as used by \citet{stock2008s,stock2012disentangling} \citep{keranen2020identification}.

Before the research I am replicating in this thesis, @kaenzig2021 studied the effects of the news shocks by the Organisation of the Petroleum Exporting Countries (OPEC) by using a similar methodology that he later used in the study of the effects EU Emission Trading system [@kaenzig2021; @kaenzig2022]. To determine the effects of oil supply news shocks, Känzig utilised the external instrument method as they are highly endogenous to the broader macroeconomy [@kaenzig2021]. This instrument was constructed by using a tight time frame around the OPEC oil supply news announcements to measure the movement of oil prices [@kaenzig2021]. Using this strategy, the researcher could build an exogenous and relevant instrument of the structural oil supply news shock [@kaenzig2021]. I will elaborate on how a similar instrument could be used in the chapter \@ref(inst). @kaenzig2021 identified short- and long-term impulse responses to a negative oil supply news shock. In the short term, the oil price increase was substantial but decreased back to the original price level with time. In contrast, oil and industrial production are not instantaneously affected, but a significant decrease in all can be detected in the long run. [@kaenzig2021]

@de2021adverse focused on their research on the effects of extreme weather events on food prices and real GDP in both developed and developing countries. In their research, they used two different instruments to estimate the effects of extreme weather events on the global agricultural commodity market and secondary impacts on economic variables [@de2021adverse]. Their research argues that the middle-income countries would be hardest hit by price shocks in the agricultural commodity market, as lower-income countries more reliant on agriculture would incur windfall profits with higher prices [@de2021adverse]. They also suggest that previous research has undervalued the consequences of extreme weather event-related price shocks in the agricultural commodities markets in more affluent countries [@de2021adverse]. Even though the evidence is statistically significant, the authors call for additional research to theorise the propagation channels from weather shock to the broader economy [@de2021adverse]. The findings should be treated with caution as the authors' analysis does not take account of the decrease in agricultural output capacity that might coincide with the changing climate.

Nevertheless, their research is vital in underlining the effects on high-income countries through price shocks [@de2021adverse]. With a similar focus, @faccia2021feeling studied the effects of anomalous temperatures in winter and summer on medium-term inflation in a European central bank working paper. According to the authors, medium-term inflation is non-trivially affected by extreme weather events. In addition, they also argue that climate change will affect the central banks' primary mandate of price stability [@faccia2021feeling].

 - add @stock2018 and @mertens2013dynamic

@mertens2013dynamic followed in the footsteps of @romer2010macroeconomic in further developing a synthesis of SVAR-based estimation methods and the narrative 

 - also add the @giacomini2022robust as the possible future of the SVAR-IV field

Overall, these studies highlight the value of the SVAR-IV as an instrument in trying to identify the $\dots$ 

\newpage