# Econometric approach {#econometrics}

In this section, I will describe the econometric model that I will use to identify the structural shocks using the Structural vector autoregression with instruments variables (SVAR-IV). In the formalisation of my model, I will follow in the footsteps of @kaenzig2022 and @montiel2021.    

## VAR

Presume a standard VAR model with a lag length of $p$.

\begin{equation} 
y_t = b + B_1y_{t-1}+\dots+ B_py_{t-p}+ u_t
(\#eq:svar)
\end{equation}

Where the $y_t$ refers to a $n \times 1$ vector of the observed endogenous variables at time step $t$. The $B_1,\dots, B_p$ are $n \times n$ coefficient matrices. $u_t$ is a $n \times 1$ vector of the reduced form innovations with a covariance matrix of $\Sigma$.

## Identification of the structural shocks

An integral assumption in using SVAR models is that the one-step-ahead prediction errors, i.e. innovations $u_t$ are a linear combination of a vector of mutually orthogonal structural shocks $\varepsilon_t$:

\begin{equation} 
u_t = S\varepsilon_t
(\#eq:strshock)
\end{equation}

$S$ is a nonsingular $n \times n$ structural impact matrix. Due to the orthogonality the structural the $n \times n$ covariance matrix of $\text{var}(\varepsilon_t)=\Omega$ is diagonal. Thus due to the linear mapping of the innovations and structural shocks described in Equation \@ref(eq:strshock), we can describe the covariance matrix of the innovations as:

$$
\Sigma = S \Omega S'
$$

For clarity, the $\varepsilon_{1,t}$ is defined to describe the carbon policy shock i.e. the shock of interest. The latter part of this chapter will present how, using an external instrument approach, we can identify the structural impact vector $s_1$, which is analogous to the first column of the structural impact matrix $S$.

## External instrument {#extinst}

For an external instrument $z_t$ to be useful in identifying structural shocks, it has to satisfy the following two conditions:


\begin{align}
\mathbb{E}(z_t \varepsilon_{1,t}) &= \alpha \neq 0  (\#eq:cond1)\\
\mathbb{E}(z_t \varepsilon_{i\neq 1,t}) &= 0 (\#eq:cond2)
\end{align}

 

Equation \@ref(eq:cond1) is referred to as the relevance condition and the equation \@ref(eq:cond2) as the exogeneity condition. If these conditions, in tandem with the invertibility requirement, are met, the sign and the scale of the $s_1$ can be identified by:


\begin{equation}
s_1 \propto \frac{\mathbb{E}(z_t u_t)}{\mathbb{E}(z_t u_{1,t})}
(\#eq:prop)
\end{equation}


The size of $\alpha$ in Equation \@ref(eq:cond1) can be viewed as the power of the external instrument, and it can be tested with the first-stage heteroskedasticity-robust F-statistic between the instrument and the VAR-residual. This method is further elaborated in the @stock2018, and which I also reported in chapter \@ref(firststage). After the structural impact vector has been identified, the confidence bands in IRF can be estimated with a moving block bootstrap method, also used by \citet{kaenzig2021,kaenzig2022}.

## Comparison with other identification strategies

Other possible strategies to identify the structural shocks would be to use heteroscedasticity-based identification of structural vector autoregressions or local projections. An interesting article by @plagborg2021local offers proof that local projections and SVARs estimate the same impulse responses but have different finite-sample properties [@plagborg2021local].

When comparing the results of SVAR-IV to ones produced with local projection, the variance of the impulse response functions is lower, but with a trade-off of bias in the results if the VAR is noninvertible [@wolf2020svar]. In Appendix \@ref(localprojapp), I will provide the impulse responses that are produced via the Local projection-instrument variable approach as a robustness check for the results of the baseline SVAR-IV model. The results we see are at least notionally similar and thus provide additional evidence for the reliability of the baseline model. 

Even though these would have been a reasonable choice as an identification strategy, as one of the main tasks of this thesis is to quasi-replicate the findings of \citeauthor{kaenzig2022}, I will continue with the SVAR-IV so that my findings are as comparable as possible. Additionally, I selected the SVAR-IV as my identification approach for the reliability and efficiency it offers. These strengths are paramount in estimating the responses to shocks from such a short sample. 

\newpage