\begingroup
\singlespacing

# (APPENDIX) Appendix {-} 

# Regulatory dates

| Date       | Event description                                                                                              | Type          |
|--------------|--------------------------------------------|--------------|
| 25.05.2005 | Italian phase I NAP approved                                                                                   | Free alloc.   |
| 20.06.2005 | Greek phase I NAP approved                                                                                     | Free alloc.   |
| 23.11.2005 | Court judgement on proposed amendment to NAP, UK vs Commission                                                 | Free alloc.   |
| 22.12.2005 | Further guidance on allocation plans for the 2008--2012 trading period                                         | Cap           |
| 22.02.2006 | Final UK Phase I NAP approved                                                                                  | Free alloc.   |
| 23.10.2006 | Stavros Dimas delivered the signal to tighten the cap of phase II                                              | Cap           |
| 13.11.2006 | Decision avoiding double counting of emission reductions for projects under the Kyoto Protocol                 | Intl. credits |
| 29.11.2006 | Commission decision on the NAP of several member states                                                        | Free alloc.   |
| 14.12.2006 | Decision determining the respective emission levels of the community and each member state                     | Cap           |
| 16.01.2007 | Phase II NAPs of Belgium and the Netherlands approved                                                          | Free alloc.   |
| 05.02.2007 | Slovenia phase II NAP approved                                                                                 | Free alloc.   |
| 26.02.2007 | Spain phase II NAP approved                                                                                    | Free alloc.   |
| 26.03.2007 | Phase II NAPs of Poland, France and Czech Republic approved                                                    | Free alloc.   |
| 02.04.2007 | Austrian phase II NAP approved                                                                                 | Free alloc.   |
| 16.04.2007 | Hungarian phase II NAP approved                                                                                | Free alloc.   |
| 30.04.2007 | Court order on German NAP, EnBW AG vs Commission                                                               | Free alloc.   |
| 04.05.2007 | Estonian phase II NAP approved                                                                                 | Free alloc.   |
| 15.05.2007 | Italian phase II NAP approved                                                                                  | Free alloc.   |
| 07.11.2007 | Court judgement on German NAP, Germany vs Commission                                                           | Free alloc.   |
| 08.04.2008 | Court order on German NAP, Saint-Gobain Glass GmbH vs Commission                                               | Free alloc.   |
| 23.04.2009 | Directive 2009/29/EC amending Directive 2003/87/EC to improve and extend the EU ETS                            | Cap           |
| 23.09.2009 | Court judgement on NAP, Poland vs Commission                                                                   | Free alloc.   |
| 24.12.2009 | Decision determining sectors and subsectors which have a significant risk of carbon leakage                    | Free alloc.   |
| 19.04.2010 | Commission accepts Polish NAP for 2008-2012                                                                    | Free alloc.   |
| 09.07.2010 | Commission takes first step toward determining cap on emission allowances for 2013                             | Cap           |
| 14.07.2010 | Member states back Commission proposed rules for auctioning of allowances                                      | Auction       |
| 22.10.2010 | Cap on emission allowances for 2013 adopted                                                                    | Cap           |
| 12.11.2010 | Commission formally adopted the regulation on auctioning                                                       | Auction       |
| 25.11.2010 | Commission presents a proposal to restrict the use of credits from industrial gas projects                     | Intl. credits |
| 15.12.2010 | Climate Change Committee supported the proposal on how to allocate emissions rights                            | Free alloc.   |
| 21.01.2011 | Member states voted to support the ban on the use of certain industrial gas credits                            | Intl. credits |
| 15.03.2011 | Commission proposed that 120 million allowances to be auctioned in 2012                                        | Auction       |
| 22.03.2011 | Court judgement on NAP, Latvia vs Commission                                                                   | Free alloc.   |
| 29.03.2011 | Decision on transitional free allocation of allowances to the power sector                                     | Free alloc.   |
| 27.04.2011 | Decision 2011/278/EU on transitional Union-wide rules for harmonized free allocation of allowances             | Free alloc.   |
| 29.04.2011 | Commission rejects Estonia's revised NAP for 2008-2012                                                         | Free alloc.   |
| 07.06.2011 | Commission adopts ban on the use of industrial gas credits                                                     | Intl. credits |
| 13.07.2011 | Member states agree to auction 120 million phase III allowances in 2012                                        | Auction       |
| 26.09.2011 | Commission sets the rules for allocation of free emissions allowances to airlines                              | Free alloc.   |
| 14.11.2011 | Clarification on the use of international credits in the third trading phase                                   | Intl. credits |
| 23.11.2011 | Regulation 1210/2011 determining the volume of allowances to be auctioned prior to 2013                        | Auction       |
| 25.11.2011 | Update on preparatory steps for auctioning of phase 3 allowances                                               | Auction       |
| 05.12.2011 | Commission decision on revised Estonian NAP for 2008-2012                                                      | Free alloc.   |
| 29.03.2012 | Court judgments on NAPs for Estonia and Poland                                                                 | Free alloc.   |
| 02.05.2012 | Commission publishes guidelines for review of GHG inventories in view of setting national limits for 2013-2020 | Cap           |
| 23.05.2012 | Commission clears temporary free allowances for power plants in Cyprus, Estonia and Lithuania                  | Free alloc.   |
| 05.06.2012 | Commission publishes guidelines on State aid measures in the context of the post-2012 trading scheme           | Free alloc.   |
| 06.07.2012 | Commission clears temporary free allowances for power plants in Bulgaria, Czech Republic and Romania           | Free alloc.   |
| 13.07.2012 | Commission rules on temporary free allowances for power plants in Poland                                       | Free alloc.   |
| 25.07.2012 | Commission proposed to backload certain allowances from 2013-2015 to the end of phase III                      | Auction       |
| 12.11.2012 | Commission submits amendment to back-load 900 million allowances to the years 2019-2020                        | Auction       |
| 14.11.2012 | Commission presents options to reform the ETS to address growing supply-demand imbalance                       | Cap           |
| 16.11.2012 | Auctions for 2012 aviation allowances put on hold                                                              | Auction       |
| 30.11.2012 | Commission rules on temporary free allowances for power plants in Hungary                                      | Free alloc.   |
| 25.01.2013 | Update on free allocation of allowances in 2013                                                                | Free alloc.   |
| 28.02.2013 | Free allocation of 2013 aviation allowances postponed                                                          | Free alloc.   |
| 25.03.2013 | Auctions of aviation allowances not to resume before June                                                      | Auction       |
| 16.04.2013 | The European Parliament voted against the Commission's back-loading proposal                                   | Auction       |
| 05.06.2013 | Commission submits proposal for international credit entitlements for 2013 to 2020                             | Intl. credits |
| 03.07.2013 | The European Parliament voted for the carbon market back-loading proposal                                      | Auction       |
| 10.07.2013 | Member states approve addition of sectors to the carbon leakage list for 2014                                  | Free alloc.   |
| 30.07.2013 | Update on industrial free allocation for phase III                                                             | Free alloc.   |
| 05.09.2013 | Commission finalized decision on industrial free allocation for phase three                                    | Free alloc.   |
| 26.09.2013 | Update on number of aviation allowances to be auctioned in 2012                                                | Auction       |
| 08.11.2013 | Member states endorsed negotiations on the back-loading proposal                                               | Auction       |
| 21.11.2013 | Commission submitted non-paper on back-loading to the EU Climate Change Committee                              | Auction       |
| 10.12.2013 | European Parliament voted for the back-loading proposal                                                        | Auction       |
| 11.12.2013 | Climate Change Committee makes progress on implementation of the back-loading propsal                          | Auction       |
| 18.12.2013 | Commission gives green light for a first set of member states to allocate allowances for calendar year 2013    | Free alloc.   |
| 08.01.2014 | Climate Change Committee agrees back-loading                                                                   | Auction       |
| 22.01.2014 | Commission proposed to establish a market stability reserve for phase V                                        | Cap           |
| 26.02.2014 | Commission gives green light for free allocation by all member states                                          | Free alloc.   |
| 27.02.2014 | Back-loading: 2014 auction volume reduced by 400 million allowances                                            | Auction       |
| 13.03.2014 | Commission approves first batch of international credit entitlement tables                                     | Intl. credits |
| 28.03.2014 | Commission approves second batch of international credit entitlement tables                                    | Intl. credits |
| 04.04.2014 | Update on approval of international credit entitlement tables                                                  | Intl. credits |
| 11.04.2014 | Commission approves four more international credit entitlement tables                                          | Intl. credits |
| 23.04.2014 | Commission approves final international credit entitlement tables                                              | Intl. credits |
| 02.05.2014 | Commission published the number of international credits exchanged                                             | Intl. credits |
| 05.05.2014 | Commission submits proposed carbon leakage list for 2015-2019                                                  | Free alloc.   |
| 04.06.2014 | Auctioning of aviation allowances to restart in September                                                      | Auction       |
| 04.07.2014 | Commission published the first update on the allocation of allowances from the New Entrants' Reserve           | Free alloc.   |
| 09.07.2014 | Climate Change Committee agrees proposed carbon leakage list for the period 2015-2019                          | Free alloc.   |
| 27.10.2014 | Commission adopts the carbon leakage list for the period 2015-2019                                             | Free alloc.   |
| 04.11.2014 | Updated information on exchange and international credit use                                                   | Intl. credits |
| 04.05.2015 | Updated information on exchange and international credit use                                                   | Intl. credits |
| 15.07.2015 | Proposal to revise the EU emissions trading system for the period after 2020                                   | Cap           |
| 23.07.2015 | Commission publishes status update for New Entrants' Reserve and allocation reductions                         | Free alloc.   |
| 04.11.2015 | Updated information on exchange and international credit use                                                   | Intl. credits |
| 15.01.2016 | Commission publishes status update for New Entrants' Reserve                                                   | Free alloc.   |
| 28.04.2016 | Court judgment on free allocation in the EU ETS for the period 2013-2020                                       | Free alloc.   |
| 02.05.2016 | Updated information on exchange and international credit use                                                   | Intl. credits |
| 23.06.2016 | Following court judgement, commission to modify cross-sectoral correction factor for 2018-2020                 | Free alloc.   |
| 15.07.2016 | Commission published a status update on the allocation of allowances from the New Entrants' Reserve 2013-2020  | Free alloc.   |
| 08.09.2016 | Court judgment on free allocation in the EU ETS for the period 2013-2020                                       | Free alloc.   |
| 04.11.2016 | Updated information on exchange and international credit use                                                   | Intl. credits |
| 16.01.2017 | Commission publishes status update for New Entrants' Reserve                                                   | Free alloc.   |
| 24.01.2017 | Commission adopts Decision to implement Court ruling on the cross-sectoral correction factor                   | Free alloc.   |
| 15.02.2017 | European Parliament voted in support of the revision of the ETS Directive for the period after 2021            | Cap           |
| 27.04.2017 | Climate Change Committee approves technical changes to auction rules                                           | Auction       |
| 02.05.2017 | Updated information on exchange and international credit use                                                   | Intl. credits |
| 12.05.2017 | Commission publishes first surplus indicator for ETS Market Stability Reserve                                  | Auction       |
| 17.07.2017 | Commission publishes status update for New Entrants' Reserve                                                   | Free alloc.   |
| 26.07.2017 | Court judgment again confirms benchmarks for free allocation of ETS allowances for 2013-2020                   | Free alloc.   |
| 06.11.2017 | Updated information on exchange and international credit use                                                   | Intl. credits |
| 15.01.2018 | Commission publishes status update for New Entrants' Reserve                                                   | Free alloc.   |
| 04.05.2018 | Updated information on exchange and international credit use                                                   | Intl. credits |
| 08.05.2018 | Commission Notice on the preliminary carbon leakage list for phase IV (2021-2030)                              | Free alloc.   |
| 15.05.2018 | ETS Market Stability Reserve will start by reducing auction volume by almost 265 million allowances            | Auction       |
| 16.07.2018 | Commission publishes status update for New Entrants' Reserve                                                   | Free alloc.   |
| 30.10.2018 | Commission adopts amendment to ETS auctioning regulation                                                       | Auction       |
| 06.11.2018 | Updated information on exchange and international credit use                                                   | Intl. credits |
| 05.12.2018 | Poland's 2019 auctions to include some allowances not used for power sector modernization                      | Auction       |

:Känzig regulatory dates

| Dates      | Event description                                                                                                                                                    | Type          |
|---------------|-------------------------------------------|---------------|
| 07.01.2019 | ETS Auctioning Regulation amendment: auctions on renewed opt-out platform for Germany to resume soon                                                                 | Auction       |
| 15.01.2019 | Commission publishes status update for New Entrants' Reserve                                                                                                         | Free alloc.   |
| 15.02.2019 | Adoption of the Delegated Decision on the carbon leakage list for 2021-2030                                                                                          | Free alloc.   |
| 23.04.2019 | EU Emissions Trading System: Iceland, Liechtenstein and Norway to start auctions on the common auction platform soon                                                 | Auction       |
| 15.05.2019 | ETS Market Stability Reserve to reduce auction volume by almost 400 million allowances between September 2019 and August 2020                                        | Auction       |
| 16.05.2019 | Revised 2019 auction calendars including EEA EFTA volumes published                                                                                                  | Auction       |
| 11.06.2019 | Draft implementing regulation on the free allocation adjustments due to activity level changes                                                                       | Free alloc.   |
| 12.06.2019 | Poland's 2020 auction volume to include allowances not used for power sector modernisation                                                                           | Auction       |
| 19.06.2019 | Updated information on exchange and international credit use in the EU ETS                                                                                           | Intl. credits |
| 15.07.2019 | Commission publishes status update for New Entrants' Reserve                                                                                                         | Free alloc.   |
| 28.08.2019 | Commission amends ETS Auctioning Regulation for phase 4                                                                                                              | Auction       |
| 31.10.2019 | Adoption of the Regulation on adjustments to free allocation of emission allowances due to activity level changes                                                    | Free alloc.   |
| 05.11.2019 | 2020 auction calendars for aviation allowances published                                                                                                             | Auction       |
| 08.11.2019 | Auctioning Regulation amendment for phase 4 of the EU ETS published and to enter into force                                                                          | Auction       |
| 09.12.2019 | Agreement on linking the emissions trading systems of the EU and Switzerland                                                                                         | Intl. credits |
| 15.01.2020 | Commission publishes status update for New Entrants' Reserve                                                                                                         | Free alloc.   |
| 31.01.2020 | Lifting the suspension of UK-related processes in the Union Registry of the EU ETS                                                                                   | Intl. credits |
| 06.05.2020 | Provisional solution for transfer of allowances between EU and Swiss emissions trading registries postponed                                                          | Intl. credits |
| 08.05.2020 | ETS Market Stability Reserve to reduce auction volume by over 330 million allowances between September 2020 and August 2021                                          | Auction       |
| 05.08.2020 | 2020 calendar for transfers of allowances between the EU and Swiss emission trading registries                                                                       | Intl. credits |
| 27.11.2020 | 2021 calendar for transfers of allowances between the EU and Swiss emission trading registries                                                                       | Intl. credits |
| 11.12.2020 | Further information on the start of phase 4 of the EU ETS in 2021: emission allowances to be issued for aircraft operators and the Market Stability Reserve          | Auction       |
| 15.03.2021 | Adoption of the Regulation determining benchmark values for free allocation for the period 2021-2025                                                                 | Free alloc.   |
| 21.04.2021 | Commission welcomes provisional agreement on the European Climate Law                                                                                                | Cap           |
| 12.05.2021 | ETS Market Stability Reserve to reduce auction volume by over 378 million allowances between September 2021 and August 2022                                          | Auction       |
| 25.05.2021 | Updated information on exchange and international credits' use in the EU ETS                                                                                         | Intl. credits |
| 31.05.2021 | Commission adopts the uniform cross-sectoral correction factor to be applied to free allocation for 2021 to 2025 in EU ETS                                           | Free alloc.   |
| 29.06.2021 | Commission publishes the national allocation tables of Member States for EU ETS stationary installations eligible to receive free allocation in the period 2021-2025 | Free alloc.   |
| 22.07.2021 | Revised 2021 and 2022 auction calendars published                                                                                                                    | Auction       |
| 15.11.2021 | Calendar 2022 for the execution of transfers between the emission trading registries of the EU and Switzerland                                                       | Intl. credits |

: My regulatory days

\endgroup