---
documentclass: article
bibliography: bibliography.bib
biblio-style: "apalike"
fontsize: 12pt
papersize: a4
linestretch: 1.5
link-citations: yes
---

\newpage

```{r setup-index, results=FALSE, message=FALSE, warning=FALSE, include=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.width = 7,
                      fig.height = 5,
                      fig.align = 'left')
library(ggplot2)
library(tidyverse)
library(readxl)
library(dplyr)

source('gradu_read_data.R', encoding = 'UTF-8')
```


# Introduction {#intro}

The Finnish government has pledged to reduce carbon dioxide emissions in an ambitious timescale. In the Government Programme, the goal of carbon neutrality is set to be achieved by 2035 [@hallitus2019]. For the goal to be completed, Finland would need to become one of the world's first countries with fossil fuel-free energy production. The energy sector's transition is in full force, as the total greenhouse emissions have decreased by twenty-one per cent since 1990 [@statfin2022]. 

Additionally, for the Finnish government to meet the goals set by the Paris Agreement, it will need drastic and urgent measures. In contrast to the topicality of this subject, there has yet to research on the macroeconomic impacts on the Finnish economy by the previously implemented EU-wide carbon emission reduction policies. This is a 

Research done by \citeauthor{kaenzig2022} will be my thesis's main inspiration. I will quasi-replicate his findings on the effects of the carbon policy shocks, changing the target variables from a European-wide context to the Finnish economy. Additionally, I will extend the carbon policy shock time series to the end of the year 2021.  

The concentration on the EU Emission trading system (EU ETS) is warranted as it is a policy tool implemented in a sizable economy, and it has reached maturity with several phases of policy development. This study aims to contribute to this growing area of research by exploring the effects of policy shocks produced by updating the framework of the EU ETS on the Finnish economy. The provide new descriptive results on the response of the Finnish economy. 

\newpage